//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: google/iam/v1/iam_policy.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// API Overview
///
/// Manages Identity and Access Management (IAM) policies.
///
/// Any implementation of an API that offers access control features
/// implements the google.iam.v1.IAMPolicy interface.
///
/// ## Data model
///
/// Access control is applied when a principal (user or service account), takes
/// some action on a resource exposed by a service. Resources, identified by
/// URI-like names, are the unit of access control specification. Service
/// implementations can choose the granularity of access control and the
/// supported permissions for their resources.
/// For example one database service may allow access control to be
/// specified only at the Table level, whereas another might allow access control
/// to also be specified at the Column level.
///
/// ## Policy Structure
///
/// See google.iam.v1.Policy
///
/// This is intentionally not a CRUD style API because access control policies
/// are created and deleted implicitly with the resources to which they are
/// attached.
///
/// Usage: instantiate `Google_Iam_V1_IAMPolicyClient`, then call methods of this protocol to make API calls.
public protocol Google_Iam_V1_IAMPolicyClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol? { get }

  func setIamPolicy(
    _ request: Google_Iam_V1_SetIamPolicyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy>

  func getIamPolicy(
    _ request: Google_Iam_V1_GetIamPolicyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy>

  func testIamPermissions(
    _ request: Google_Iam_V1_TestIamPermissionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse>
}

extension Google_Iam_V1_IAMPolicyClientProtocol {
  public var serviceName: String {
    return "google.iam.v1.IAMPolicy"
  }

  /// Sets the access control policy on the specified resource. Replaces any
  /// existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
  ///
  /// - Parameters:
  ///   - request: Request to send to SetIamPolicy.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func setIamPolicy(
    _ request: Google_Iam_V1_SetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy> {
    return self.makeUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.setIamPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetIamPolicyInterceptors() ?? []
    )
  }

  /// Gets the access control policy for a resource.
  /// Returns an empty policy if the resource exists and does not have a policy
  /// set.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIamPolicy.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getIamPolicy(
    _ request: Google_Iam_V1_GetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy> {
    return self.makeUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.getIamPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIamPolicyInterceptors() ?? []
    )
  }

  /// Returns permissions that a caller has on the specified resource.
  /// If the resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  ///
  /// - Parameters:
  ///   - request: Request to send to TestIamPermissions.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func testIamPermissions(
    _ request: Google_Iam_V1_TestIamPermissionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse> {
    return self.makeUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.testIamPermissions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTestIamPermissionsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Google_Iam_V1_IAMPolicyClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Google_Iam_V1_IAMPolicyNIOClient")
public final class Google_Iam_V1_IAMPolicyClient: Google_Iam_V1_IAMPolicyClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the google.iam.v1.IAMPolicy service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Google_Iam_V1_IAMPolicyNIOClient: Google_Iam_V1_IAMPolicyClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol?

  /// Creates a client for the google.iam.v1.IAMPolicy service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// API Overview
///
/// Manages Identity and Access Management (IAM) policies.
///
/// Any implementation of an API that offers access control features
/// implements the google.iam.v1.IAMPolicy interface.
///
/// ## Data model
///
/// Access control is applied when a principal (user or service account), takes
/// some action on a resource exposed by a service. Resources, identified by
/// URI-like names, are the unit of access control specification. Service
/// implementations can choose the granularity of access control and the
/// supported permissions for their resources.
/// For example one database service may allow access control to be
/// specified only at the Table level, whereas another might allow access control
/// to also be specified at the Column level.
///
/// ## Policy Structure
///
/// See google.iam.v1.Policy
///
/// This is intentionally not a CRUD style API because access control policies
/// are created and deleted implicitly with the resources to which they are
/// attached.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Google_Iam_V1_IAMPolicyAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol? { get }

  func makeSetIamPolicyCall(
    _ request: Google_Iam_V1_SetIamPolicyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy>

  func makeGetIamPolicyCall(
    _ request: Google_Iam_V1_GetIamPolicyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy>

  func makeTestIamPermissionsCall(
    _ request: Google_Iam_V1_TestIamPermissionsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Iam_V1_IAMPolicyAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Iam_V1_IAMPolicyClientMetadata.serviceDescriptor
  }

  public var interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSetIamPolicyCall(
    _ request: Google_Iam_V1_SetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy> {
    return self.makeAsyncUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.setIamPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetIamPolicyInterceptors() ?? []
    )
  }

  public func makeGetIamPolicyCall(
    _ request: Google_Iam_V1_GetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy> {
    return self.makeAsyncUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.getIamPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIamPolicyInterceptors() ?? []
    )
  }

  public func makeTestIamPermissionsCall(
    _ request: Google_Iam_V1_TestIamPermissionsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.testIamPermissions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTestIamPermissionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Iam_V1_IAMPolicyAsyncClientProtocol {
  public func setIamPolicy(
    _ request: Google_Iam_V1_SetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Iam_V1_Policy {
    return try await self.performAsyncUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.setIamPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetIamPolicyInterceptors() ?? []
    )
  }

  public func getIamPolicy(
    _ request: Google_Iam_V1_GetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Iam_V1_Policy {
    return try await self.performAsyncUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.getIamPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIamPolicyInterceptors() ?? []
    )
  }

  public func testIamPermissions(
    _ request: Google_Iam_V1_TestIamPermissionsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Iam_V1_TestIamPermissionsResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Iam_V1_IAMPolicyClientMetadata.Methods.testIamPermissions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTestIamPermissionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Google_Iam_V1_IAMPolicyAsyncClient: Google_Iam_V1_IAMPolicyAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Google_Iam_V1_IAMPolicyClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'setIamPolicy'.
  func makeSetIamPolicyInterceptors() -> [ClientInterceptor<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when invoking 'getIamPolicy'.
  func makeGetIamPolicyInterceptors() -> [ClientInterceptor<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when invoking 'testIamPermissions'.
  func makeTestIamPermissionsInterceptors() -> [ClientInterceptor<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse>]
}

public enum Google_Iam_V1_IAMPolicyClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "IAMPolicy",
    fullName: "google.iam.v1.IAMPolicy",
    methods: [
      Google_Iam_V1_IAMPolicyClientMetadata.Methods.setIamPolicy,
      Google_Iam_V1_IAMPolicyClientMetadata.Methods.getIamPolicy,
      Google_Iam_V1_IAMPolicyClientMetadata.Methods.testIamPermissions,
    ]
  )

  public enum Methods {
    public static let setIamPolicy = GRPCMethodDescriptor(
      name: "SetIamPolicy",
      path: "/google.iam.v1.IAMPolicy/SetIamPolicy",
      type: GRPCCallType.unary
    )

    public static let getIamPolicy = GRPCMethodDescriptor(
      name: "GetIamPolicy",
      path: "/google.iam.v1.IAMPolicy/GetIamPolicy",
      type: GRPCCallType.unary
    )

    public static let testIamPermissions = GRPCMethodDescriptor(
      name: "TestIamPermissions",
      path: "/google.iam.v1.IAMPolicy/TestIamPermissions",
      type: GRPCCallType.unary
    )
  }
}

/// API Overview
///
/// Manages Identity and Access Management (IAM) policies.
///
/// Any implementation of an API that offers access control features
/// implements the google.iam.v1.IAMPolicy interface.
///
/// ## Data model
///
/// Access control is applied when a principal (user or service account), takes
/// some action on a resource exposed by a service. Resources, identified by
/// URI-like names, are the unit of access control specification. Service
/// implementations can choose the granularity of access control and the
/// supported permissions for their resources.
/// For example one database service may allow access control to be
/// specified only at the Table level, whereas another might allow access control
/// to also be specified at the Column level.
///
/// ## Policy Structure
///
/// See google.iam.v1.Policy
///
/// This is intentionally not a CRUD style API because access control policies
/// are created and deleted implicitly with the resources to which they are
/// attached.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Google_Iam_V1_IAMPolicyProvider: CallHandlerProvider {
  var interceptors: Google_Iam_V1_IAMPolicyServerInterceptorFactoryProtocol? { get }

  /// Sets the access control policy on the specified resource. Replaces any
  /// existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
  func setIamPolicy(request: Google_Iam_V1_SetIamPolicyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Iam_V1_Policy>

  /// Gets the access control policy for a resource.
  /// Returns an empty policy if the resource exists and does not have a policy
  /// set.
  func getIamPolicy(request: Google_Iam_V1_GetIamPolicyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Iam_V1_Policy>

  /// Returns permissions that a caller has on the specified resource.
  /// If the resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  func testIamPermissions(request: Google_Iam_V1_TestIamPermissionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Iam_V1_TestIamPermissionsResponse>
}

extension Google_Iam_V1_IAMPolicyProvider {
  public var serviceName: Substring {
    return Google_Iam_V1_IAMPolicyServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SetIamPolicy":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_SetIamPolicyRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_Policy>(),
        interceptors: self.interceptors?.makeSetIamPolicyInterceptors() ?? [],
        userFunction: self.setIamPolicy(request:context:)
      )

    case "GetIamPolicy":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_GetIamPolicyRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_Policy>(),
        interceptors: self.interceptors?.makeGetIamPolicyInterceptors() ?? [],
        userFunction: self.getIamPolicy(request:context:)
      )

    case "TestIamPermissions":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_TestIamPermissionsRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_TestIamPermissionsResponse>(),
        interceptors: self.interceptors?.makeTestIamPermissionsInterceptors() ?? [],
        userFunction: self.testIamPermissions(request:context:)
      )

    default:
      return nil
    }
  }
}

/// API Overview
///
/// Manages Identity and Access Management (IAM) policies.
///
/// Any implementation of an API that offers access control features
/// implements the google.iam.v1.IAMPolicy interface.
///
/// ## Data model
///
/// Access control is applied when a principal (user or service account), takes
/// some action on a resource exposed by a service. Resources, identified by
/// URI-like names, are the unit of access control specification. Service
/// implementations can choose the granularity of access control and the
/// supported permissions for their resources.
/// For example one database service may allow access control to be
/// specified only at the Table level, whereas another might allow access control
/// to also be specified at the Column level.
///
/// ## Policy Structure
///
/// See google.iam.v1.Policy
///
/// This is intentionally not a CRUD style API because access control policies
/// are created and deleted implicitly with the resources to which they are
/// attached.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Google_Iam_V1_IAMPolicyAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Iam_V1_IAMPolicyServerInterceptorFactoryProtocol? { get }

  /// Sets the access control policy on the specified resource. Replaces any
  /// existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
  func setIamPolicy(
    request: Google_Iam_V1_SetIamPolicyRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Iam_V1_Policy

  /// Gets the access control policy for a resource.
  /// Returns an empty policy if the resource exists and does not have a policy
  /// set.
  func getIamPolicy(
    request: Google_Iam_V1_GetIamPolicyRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Iam_V1_Policy

  /// Returns permissions that a caller has on the specified resource.
  /// If the resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  func testIamPermissions(
    request: Google_Iam_V1_TestIamPermissionsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Iam_V1_TestIamPermissionsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Iam_V1_IAMPolicyAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Iam_V1_IAMPolicyServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Google_Iam_V1_IAMPolicyServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Google_Iam_V1_IAMPolicyServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SetIamPolicy":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_SetIamPolicyRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_Policy>(),
        interceptors: self.interceptors?.makeSetIamPolicyInterceptors() ?? [],
        wrapping: { try await self.setIamPolicy(request: $0, context: $1) }
      )

    case "GetIamPolicy":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_GetIamPolicyRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_Policy>(),
        interceptors: self.interceptors?.makeGetIamPolicyInterceptors() ?? [],
        wrapping: { try await self.getIamPolicy(request: $0, context: $1) }
      )

    case "TestIamPermissions":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_TestIamPermissionsRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_TestIamPermissionsResponse>(),
        interceptors: self.interceptors?.makeTestIamPermissionsInterceptors() ?? [],
        wrapping: { try await self.testIamPermissions(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Google_Iam_V1_IAMPolicyServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'setIamPolicy'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSetIamPolicyInterceptors() -> [ServerInterceptor<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when handling 'getIamPolicy'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIamPolicyInterceptors() -> [ServerInterceptor<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when handling 'testIamPermissions'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTestIamPermissionsInterceptors() -> [ServerInterceptor<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse>]
}

public enum Google_Iam_V1_IAMPolicyServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "IAMPolicy",
    fullName: "google.iam.v1.IAMPolicy",
    methods: [
      Google_Iam_V1_IAMPolicyServerMetadata.Methods.setIamPolicy,
      Google_Iam_V1_IAMPolicyServerMetadata.Methods.getIamPolicy,
      Google_Iam_V1_IAMPolicyServerMetadata.Methods.testIamPermissions,
    ]
  )

  public enum Methods {
    public static let setIamPolicy = GRPCMethodDescriptor(
      name: "SetIamPolicy",
      path: "/google.iam.v1.IAMPolicy/SetIamPolicy",
      type: GRPCCallType.unary
    )

    public static let getIamPolicy = GRPCMethodDescriptor(
      name: "GetIamPolicy",
      path: "/google.iam.v1.IAMPolicy/GetIamPolicy",
      type: GRPCCallType.unary
    )

    public static let testIamPermissions = GRPCMethodDescriptor(
      name: "TestIamPermissions",
      path: "/google.iam.v1.IAMPolicy/TestIamPermissions",
      type: GRPCCallType.unary
    )
  }
}
